### ISSUE TITLE
generate reading text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#174]
- [x] adapt text according to `replacement...xlsx`
- [x] insert the whole of Faust II as `div` into "Faust. Eine Tragödie", i.e., after the `div` that contains "Der Tragödie Erster Theil".
- [x] #47 source: //stage/emph → hi
- [x] #46 source: name → hi
- [x] #175 source: move stage at end of sp out of sp
- [x] #178 drop some elements & list them instead
- [x] #179 handle orig
- [x]  #183  drop type='stueck' div from reading text 
- [x] #119 Insertion of emendations 
- [x] #185 error reporting for last step of #119 
- [x] #181  assign schema to reading text
- [x]  #182 define header for reading text 
- [x] #184 html: render app notes (#119) for online rendering at margin
- [x] list of witnesses referenced in the app entries

**Comment by thvitt** [comment]
witness list is in faust.xml//sourceDesc/listWit now, does this need to be rendered somewhere?

**Comment by gerritbruening** [comment]
No, that's perfect, thanks!

**Comment by gerritbruening** [comment]
Still open?

**Comment by thvitt** [comment]
#182
