### ISSUE TITLE
Überschriften, Unterüberschriften und BAs

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#331]
Siehe auch 
* #307 
* https://github.com/faustedition/xml/issues/244
* https://github.com/faustedition/xml/issues/243

Abfragen:
* //div/*[1][self::stage]
* ...

Auftrittsbezeichnungen sind unkritisch. Insbesondere im Faust II kann jedoch die Unterscheidung zwischen Unterüberschriften und erster Bühnenanweisung schwierig sein.
Indizien:
* waagerechte Linien (trennen u.U. Überschriftsbereich ab)
* Gestaltung (Klammern sprechen für BA)

**kritische** Stellen
* **Harzgebirg**
* ...
- [x] before_5987_b Unterüberschrift, weil danach waagerechter Strich
- [x] before_6307_b Kaiser und Fürsten ... Unterüberschrift, weil danach waagerechter Strich
- [x] before_6377_b Rittersaal / Dämmernde ... (http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=101&view=facsimile) Unterüberschrift, weil danach waagerechter Strich
- [x] "Hochgewölbtes, enges gotisches Zimmer ..." insgesamt lange Überschrift (Linie danach)
- [x] "Laboratorium | im Sinne des Mittelalters ..." insgesamt lange Überschrift (Linie danach)
- [x] Classische Walpurgisnacht folgt kein Text
- [x] "Pharsalische Felder, | Finsterniß" eindeutig Überschrift
- [x] "**Peneius umgeben ...**" jetzt als `stage` mit `hi` behandelt (https://github.com/faustedition/xml/issues/581)
- [x] "**Am obern Peneios wie zuvor**" ursprünglich BA (https://github.com/faustedition/xml/issues/581)
- [x] "Felsbuchten des Ägäischen Meers | **Mond im Zenith verharrend**" das zweite eher BA (so auch H.74) --> https://github.com/faustedition/xml/issues/581
- [x] "**Telchinen von Rhodus | auf Hippokampen ...**" jetzt als `stage` mit `hi` behandelt (innere Struktur analog zu ähnlichen Fällen) --> https://github.com/faustedition/xml/issues/581
- [x] Dritter Akt eindeutig (nur eine Überschrift)
- [x] "Hochgebirg, ..." sehr lang (6 Zeilen), ohne sichtbare Untergliederung. Als Überschrift behandelt.
- [x] "Auf dem Vorgebirg | **Trommeln und kriegerische Musick von unten.** | Des Kaisers Zelt wird aufgeschlagen." (Linie) Eine Haupt-, zwei Unterüberschriften
- [x] "Des Gegenkaisers Zelt, ..." eindeutig, aber lang
- [x] Offene Gegend eindeutig
- [x] "Pallaſt. | weiter Ziergarten ..."  eine Überschrift, aber lang.
- [x] Tiefe Nacht eindeutig
- [x] "Mitternacht" Unterszenenüberschrift am Kopf nachgetragen, danach folgt ohne waagerechte Linie "**Vier graue Weiber treten auf**" ohne Klammern, trotzdem als BA behandelt
- [x] Großer Vorhof ... Szenenüberschrift, danach "**Fackeln**" (aus "Vor dem Pallast"): BA aus ursprünglicher Szenenunterüberschrift (Linie)
- [x] "Grablegung" ist Unterszenenüberschrift (eindeutig, danach Sprecher + BA)
- [x] "Bergschluchten ..." ist eindeutig, fraglich ist nur der Zeilenumbruch in der Überschrift

**Comment by dietmarpravida** [comment]
ist das noch aktuell?

**Comment by gerritbruening** [comment]
Du könntest mal schauen, ob es im Faust&nbsp;I kritische Stellen gibt, die vor der Datenübergabe behandelt werden müssen. Wenn nicht, kannst du dich un-assignen.

**Comment by dietmarpravida** [comment]
* Auerbachs Keller in Leipzig. [nach Linie:] **Zeche lustiger Gesellen**
* Abend. [nach Linie:] **Ein kleines reinliches Zimmer**
* Nacht. [nach Linie:] **Straße vor Gretchens Thüre**
* Walpurgisnacht. [nach Linie:] **Harzgebirg**. Gegend von Schirke und Elend

**Comment by gerritbruening** [comment]
(vier abgehakt, ohne jetzt nochmal draufgeschaut zu haben)
"Harzgebirg" scheint mir unklar.

**Comment by dietmarpravida** [comment]
In meinen Augen bilden "Gegend von Schirke und Elend" und "Amt, Orgel und Gesang" (habe oben anscheinend eine falsche # angegeben, es gibt aber ein Issue dazu) in gewisser Hinsicht vergleichbare Fälle: beide wurden erst in der Druckvorlage (von S resp. von A) umplaziert bzw. eingefügt und sorgten für Unklarheiten.  "Harzgebirg" ist da nur das leidtragende Eement, das dann den ganzen Head in Unordnung gebracht hat.

**Comment by dietmarpravida** [comment]
ich denke, wir lassen es so, wie es jetzt im 2. Satz von Faust I ist. 

@gerritbruening Muss ich mich auch zu Faust II äußern?

**Comment by gerritbruening** [comment]
Nein, mit speziellen Fragen würde ich mich melden.

**Comment by gerritbruening** [comment]
[head.docx](https://github.com/faustedition/faust-gen-html/files/2321474/head.docx)
Hier die Überschriften.

**Comment by dietmarpravida** [comment]
jetzt nicht mehr
