### ISSUE TITLE
Include meta texts in search

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#85]
Notwendig:
- [ ] Konvertierung der Webseiten mit den Metatexten nach XHTML, entweder einmalig ([faust-web](faustedition/faust-web)) oder bei jedem Build (JTidy oder so) (pom in [faust-gen](faustedition/faust-gen))
- [ ] Definition sinnvoller Anspringpunkte (Überschriften? `<article>`? `<section>`?) und Einpflegen von IDs ([faust-web](faustedition/faust-web))
- [ ] Implementierung der Query
- [ ] Aufbereitung der Suchergebnisse (vllt. ist das mal ein Anwendungsfall für eXists KWIC-Modul)
